name: Manual release
on:
  workflow_dispatch:
    inputs:
      prerelease:
        description: 'Prerelease: true to identify the release as a prerelease. false to identify the release as a full release.'
        type: choice
        required: false
        default: 'false'
        options:
          - true
          - false
      draft:
        description: 'Draft: true to create a draft (unpublished) release, false to create a published one.'
        type: choice
        required: false
        default: 'false'
        options:
          - true
          - false
jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5.1.0
        with:
          github-token: ${{ secrets.PA_TOKEN }}
          pre-release: ${{ inputs.prerelease == 'true' }}
          version-file: './package.json,./package-lock.json'
          preset: 'conventionalcommits'
      - name: Create release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          prerelease: ${{ inputs.prerelease == 'true' }}
          draft: ${{ inputs.draft == 'true' }}
